// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdpgMXKkTYD8gYYISzrUL3DhFYzAuVuzQ',
    appId: '1:626566606424:web:0f9cdf4b7fcb24f68e242d',
    messagingSenderId: '626566606424',
    projectId: 'marketplacev4-ac6c0',
    authDomain: 'marketplacev4-ac6c0.firebaseapp.com',
    storageBucket: 'marketplacev4-ac6c0.firebasestorage.app',
    measurementId: 'G-T79G50C6SJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMid71-Zhg9651rF7Bn4HPckLRX4adtGw',
    appId: '1:626566606424:android:abd3b2141e717eb58e242d',
    messagingSenderId: '626566606424',
    projectId: 'marketplacev4-ac6c0',
    storageBucket: 'marketplacev4-ac6c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBos1Ub6lzBAvPN2m4ZEN7O9PPbdY0BzDo',
    appId: '1:626566606424:ios:1793845458227a4d8e242d',
    messagingSenderId: '626566606424',
    projectId: 'marketplacev4-ac6c0',
    storageBucket: 'marketplacev4-ac6c0.firebasestorage.app',
    iosBundleId: 'com.example.marketplaceappv4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBos1Ub6lzBAvPN2m4ZEN7O9PPbdY0BzDo',
    appId: '1:626566606424:ios:1793845458227a4d8e242d',
    messagingSenderId: '626566606424',
    projectId: 'marketplacev4-ac6c0',
    storageBucket: 'marketplacev4-ac6c0.firebasestorage.app',
    iosBundleId: 'com.example.marketplaceappv4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdpgMXKkTYD8gYYISzrUL3DhFYzAuVuzQ',
    appId: '1:626566606424:web:14a8b6b6e3a9e2b38e242d',
    messagingSenderId: '626566606424',
    projectId: 'marketplacev4-ac6c0',
    authDomain: 'marketplacev4-ac6c0.firebaseapp.com',
    storageBucket: 'marketplacev4-ac6c0.firebasestorage.app',
    measurementId: 'G-HEG17XD3MC',
  );

}